#############################################################################
# Makefile for building: libSampleQTLib.a
# Generated by qmake (3.1) (Qt 5.8.0)
# Project:  ../SampleQTLib/SampleQTLib.pro
# Template: lib
# Command: /Users/ss/Qt/5.8/ios/bin/qmake -o Makefile ../SampleQTLib/SampleQTLib.pro -spec macx-ios-clang CONFIG+=iphonesimulator CONFIG+=simulator CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DDARWIN_NO_CARBON -DQT_COMPILER_SUPPORTS_SSE2 -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_CORE_LIB
CFLAGS        = -pipe -fvisibility=hidden -fpascal-strings -fmessage-length=0 -Wno-trigraphs -Wreturn-type -Wparentheses -Wswitch -Wno-unused-parameter -Wunused-variable -Wunused-value -Wno-shorten-64-to-32 -Wno-sign-conversion -fexceptions -fasm-blocks -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wformat -Wno-missing-braces -Wno-unused-function -Wno-unused-label -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-sign-compare -Wpointer-sign -Wno-newline-eof -Wdeprecated-declarations -Winvalid-offsetof -Wno-conversion $(EXPORT_QMAKE_XARCH_CFLAGS) -g -fPIC $(EXPORT_ARCH_ARGS) -fobjc-nonfragile-abi -fobjc-legacy-dispatch -Wno-deprecated-implementations -Wprotocol -Wno-selector -Wno-strict-selector-match -Wno-undeclared-selector -fembed-bitcode-marker -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -fvisibility=hidden -fpascal-strings -fmessage-length=0 -Wno-trigraphs -Wreturn-type -Wparentheses -Wswitch -Wno-unused-parameter -Wunused-variable -Wunused-value -Wno-shorten-64-to-32 -Wno-sign-conversion -fexceptions -fasm-blocks -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wformat -Wno-missing-braces -Wno-unused-function -Wno-unused-label -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-sign-compare -Wpointer-sign -Wno-newline-eof -Wdeprecated-declarations -Winvalid-offsetof -Wno-conversion -fvisibility-inlines-hidden -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors $(EXPORT_QMAKE_XARCH_CFLAGS) -g -fPIC -std=gnu++11 $(EXPORT_ARCH_ARGS) -fobjc-nonfragile-abi -fobjc-legacy-dispatch -Wno-deprecated-implementations -Wprotocol -Wno-selector -Wno-strict-selector-match -Wno-undeclared-selector -fembed-bitcode-marker -Wall -W $(DEFINES)
INCPATH       = -I../SampleQTLib -I. -I../../Qt/5.8/ios/mkspecs/common/uikit -I../../Qt/5.8/ios/include -I../../Qt/5.8/ios/include/QtCore -I. -I../../Qt/5.8/ios/mkspecs/macx-ios-clang
QMAKE         = /Users/ss/Qt/5.8/ios/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = SampleQTLib1.0.0
DISTDIR = /Users/ss/Desktop/build-SampleQTLib-iphonesimulator_clang_Qt_5_8_0_for_iOS-Debug/.tmp/SampleQTLib1.0.0
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ../SampleQTLib/sampleqtlib.cpp 
OBJECTS       = sampleqtlib.o
DIST          = ../../Qt/5.8/ios/mkspecs/features/spec_pre.prf \
		../../Qt/5.8/ios/mkspecs/qdevice.pri \
		../../Qt/5.8/ios/mkspecs/features/device_config.prf \
		../../Qt/5.8/ios/mkspecs/common/unix.conf \
		../../Qt/5.8/ios/mkspecs/common/mac.conf \
		../../Qt/5.8/ios/mkspecs/common/uikit.conf \
		../../Qt/5.8/ios/mkspecs/common/ios.conf \
		../../Qt/5.8/ios/mkspecs/common/sanitize.conf \
		../../Qt/5.8/ios/mkspecs/common/gcc-base.conf \
		../../Qt/5.8/ios/mkspecs/common/gcc-base-mac.conf \
		../../Qt/5.8/ios/mkspecs/common/clang.conf \
		../../Qt/5.8/ios/mkspecs/common/clang-mac.conf \
		../../Qt/5.8/ios/mkspecs/common/ios/clang.conf \
		../../Qt/5.8/ios/mkspecs/common/ios/qmake.conf \
		../../Qt/5.8/ios/mkspecs/qconfig.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dextras.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_charts.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_charts_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_datavisualization.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_gamepad.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_help.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_location.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_networkauth.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_purchasing.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_script.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_webview.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_zlib_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_darwingamepad.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_gltfsceneio.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qavfcamera.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qavfmediaplayer.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qgif.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qicns.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qico.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qios.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qiosnsphotolibrarysupport.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qjpeg.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qmacjp2.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qminimal.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qmldbg_debugger.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qmldbg_inspector.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qmldbg_local.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qmldbg_native.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qmldbg_profiler.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qmldbg_quickprofiler.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qmldbg_server.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qmldbg_tcp.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qoffscreen.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qsqlite.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qsvg.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qsvgicon.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtaudio_coreaudio.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtexttospeech_speechios.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtga.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtgeoservices_esri.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtgeoservices_mapbox.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtgeoservices_nokia.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtgeoservices_osm.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtiff.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtposition_cl.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtsensors_generic.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtsensors_ios.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qwbmp.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qwebp.pri \
		../../Qt/5.8/ios/mkspecs/features/qt_functions.prf \
		../../Qt/5.8/ios/mkspecs/features/qt_config.prf \
		../../Qt/5.8/ios/mkspecs/features/uikit/qt_config.prf \
		../../Qt/5.8/ios/mkspecs/macx-ios-clang/qmake.conf \
		../../Qt/5.8/ios/mkspecs/features/spec_post.prf \
		../SampleQTLib/.qmake.stash \
		../../Qt/5.8/ios/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.8/ios/mkspecs/features/mac/sdk.prf \
		../../Qt/5.8/ios/mkspecs/features/uikit/sdk.prf \
		../../Qt/5.8/ios/mkspecs/features/toolchain.prf \
		../../Qt/5.8/ios/mkspecs/features/mac/toolchain.prf \
		../../Qt/5.8/ios/mkspecs/features/default_pre.prf \
		../../Qt/5.8/ios/mkspecs/features/mac/default_pre.prf \
		../../Qt/5.8/ios/mkspecs/features/uikit/default_pre.prf \
		../../Qt/5.8/ios/mkspecs/features/resolve_config.prf \
		../../Qt/5.8/ios/mkspecs/features/uikit/resolve_config.prf \
		../../Qt/5.8/ios/mkspecs/features/default_post.prf \
		../../Qt/5.8/ios/mkspecs/features/mac/default_post.prf \
		../../Qt/5.8/ios/mkspecs/features/uikit/default_post.prf \
		../../Qt/5.8/ios/mkspecs/macx-ios-clang/features/default_post.prf \
		../../Qt/5.8/ios/mkspecs/features/mac/objective_c.prf \
		../../Qt/5.8/ios/mkspecs/features/qml_debug.prf \
		../../Qt/5.8/ios/mkspecs/features/uikit/bitcode.prf \
		../../Qt/5.8/ios/mkspecs/features/warn_on.prf \
		../../Qt/5.8/ios/mkspecs/features/qt.prf \
		../../Qt/5.8/ios/mkspecs/features/uikit/qt.prf \
		../../Qt/5.8/ios/mkspecs/features/resources.prf \
		../../Qt/5.8/ios/mkspecs/features/moc.prf \
		../../Qt/5.8/ios/mkspecs/features/unix/thread.prf \
		../../Qt/5.8/ios/mkspecs/features/qmake_use.prf \
		../../Qt/5.8/ios/mkspecs/features/file_copies.prf \
		../../Qt/5.8/ios/mkspecs/features/mac/rez.prf \
		../../Qt/5.8/ios/mkspecs/features/mac/asset_catalogs.prf \
		../../Qt/5.8/ios/mkspecs/features/testcase_targets.prf \
		../../Qt/5.8/ios/mkspecs/features/uikit/testcase_targets.prf \
		../../Qt/5.8/ios/mkspecs/features/exceptions.prf \
		../../Qt/5.8/ios/mkspecs/features/yacc.prf \
		../../Qt/5.8/ios/mkspecs/features/lex.prf \
		../SampleQTLib/SampleQTLib.pro ../SampleQTLib/sampleqtlib.h ../SampleQTLib/sampleqtlib.cpp
QMAKE_TARGET  = SampleQTLib
DESTDIR       = 
TARGET        = libSampleQTLib.a

####### Custom Variables
EXPORT_QMAKE_XARCH_CFLAGS_x86_64 = -Xarch_x86_64 -mios-simulator-version-min=7.0 -Xarch_x86_64 -isysroot/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.2.sdk
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_QMAKE_XARCH_LFLAGS = $(EXPORT_QMAKE_XARCH_CFLAGS_armv7) $(EXPORT_QMAKE_XARCH_CFLAGS_arm64) $(EXPORT_QMAKE_XARCH_CFLAGS_i386) $(EXPORT_QMAKE_XARCH_CFLAGS_x86_64)
EXPORT_QMAKE_XARCH_LFLAGS_i386 = -Xarch_i386 -mios-simulator-version-min=7.0 -Xarch_i386 -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.2.sdk
EXPORT_QMAKE_XARCH_CFLAGS_arm64 = -Xarch_arm64 -miphoneos-version-min=7.0 -Xarch_arm64 -isysroot/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.2.sdk
EXPORT_QMAKE_XARCH_LFLAGS_arm64 = -Xarch_arm64 -miphoneos-version-min=7.0 -Xarch_arm64 -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.2.sdk
EXPORT_QMAKE_XARCH_LFLAGS_x86_64 = -Xarch_x86_64 -mios-simulator-version-min=7.0 -Xarch_x86_64 -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.2.sdk
EXPORT_QMAKE_XARCH_CFLAGS_armv7 = -Xarch_armv7 -miphoneos-version-min=7.0 -Xarch_armv7 -isysroot/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.2.sdk
EXPORT_QMAKE_XARCH_CFLAGS_i386 = -Xarch_i386 -mios-simulator-version-min=7.0 -Xarch_i386 -isysroot/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.2.sdk
EXPORT_QMAKE_XARCH_LFLAGS_armv7 = -Xarch_armv7 -miphoneos-version-min=7.0 -Xarch_armv7 -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.2.sdk
EXPORT_VALID_ARCHS = armv7 arm64 i386 x86_64
EXPORT_QMAKE_XARCH_CFLAGS = $(EXPORT_QMAKE_XARCH_CFLAGS_armv7) $(EXPORT_QMAKE_XARCH_CFLAGS_arm64) $(EXPORT_QMAKE_XARCH_CFLAGS_i386) $(EXPORT_QMAKE_XARCH_CFLAGS_x86_64)
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))


first: all
####### Build rules

staticlib: $(TARGET)

$(TARGET): /Users/ss/Qt/5.8/ios/lib/libQt5Core_debug.a $(OBJECTS) $(OBJCOMP) 
	-$(DEL_FILE) $(TARGET)
	$(AR) $(DESTDIR)$(TARGET) $(OBJECTS)
	$(RANLIB) $(TARGET)


Makefile: ../SampleQTLib/SampleQTLib.pro ../../Qt/5.8/ios/mkspecs/macx-ios-clang/qmake.conf ../../Qt/5.8/ios/mkspecs/features/spec_pre.prf \
		../../Qt/5.8/ios/mkspecs/qdevice.pri \
		../../Qt/5.8/ios/mkspecs/features/device_config.prf \
		../../Qt/5.8/ios/mkspecs/common/unix.conf \
		../../Qt/5.8/ios/mkspecs/common/mac.conf \
		../../Qt/5.8/ios/mkspecs/common/uikit.conf \
		../../Qt/5.8/ios/mkspecs/common/ios.conf \
		../../Qt/5.8/ios/mkspecs/common/sanitize.conf \
		../../Qt/5.8/ios/mkspecs/common/gcc-base.conf \
		../../Qt/5.8/ios/mkspecs/common/gcc-base-mac.conf \
		../../Qt/5.8/ios/mkspecs/common/clang.conf \
		../../Qt/5.8/ios/mkspecs/common/clang-mac.conf \
		../../Qt/5.8/ios/mkspecs/common/ios/clang.conf \
		../../Qt/5.8/ios/mkspecs/common/ios/qmake.conf \
		../../Qt/5.8/ios/mkspecs/qconfig.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dcore.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dextras.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dinput.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dquick.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_3drender.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_charts.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_charts_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_clucene_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_concurrent.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_core.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_core_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_datavisualization.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_gamepad.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_gui.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_gui_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_help.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_help_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_location.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_location_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_multimedia.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_network.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_network_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_networkauth.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_nfc.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_opengl.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_positioning.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_printsupport.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_purchasing.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_qml.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_qml_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_qmltest.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_quick.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_quick_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_script.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_script_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_scripttools.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_scxml.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_sensors.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_sql.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_sql_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_svg.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_svg_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_testlib.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_uitools.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_webchannel.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_websockets.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_webview.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_webview_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_widgets.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_xml.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_xml_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_lib_zlib_private.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_darwingamepad.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_gltfsceneio.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qavfcamera.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qavfmediaplayer.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qgif.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qicns.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qico.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qios.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qiosnsphotolibrarysupport.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qjpeg.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qmacjp2.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qminimal.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qmldbg_debugger.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qmldbg_inspector.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qmldbg_local.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qmldbg_native.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qmldbg_profiler.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qmldbg_quickprofiler.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qmldbg_server.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qmldbg_tcp.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qoffscreen.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qsqlite.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qsvg.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qsvgicon.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtaudio_coreaudio.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtexttospeech_speechios.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtga.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtgeoservices_esri.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtgeoservices_mapbox.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtgeoservices_nokia.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtgeoservices_osm.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtiff.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtposition_cl.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtsensors_generic.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtsensors_ios.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qwbmp.pri \
		../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qwebp.pri \
		../../Qt/5.8/ios/mkspecs/features/qt_functions.prf \
		../../Qt/5.8/ios/mkspecs/features/qt_config.prf \
		../../Qt/5.8/ios/mkspecs/features/uikit/qt_config.prf \
		../../Qt/5.8/ios/mkspecs/macx-ios-clang/qmake.conf \
		../../Qt/5.8/ios/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Qt/5.8/ios/mkspecs/features/exclusive_builds.prf \
		../../Qt/5.8/ios/mkspecs/features/mac/sdk.prf \
		../../Qt/5.8/ios/mkspecs/features/uikit/sdk.prf \
		../../Qt/5.8/ios/mkspecs/features/toolchain.prf \
		../../Qt/5.8/ios/mkspecs/features/mac/toolchain.prf \
		../../Qt/5.8/ios/mkspecs/features/default_pre.prf \
		../../Qt/5.8/ios/mkspecs/features/mac/default_pre.prf \
		../../Qt/5.8/ios/mkspecs/features/uikit/default_pre.prf \
		../../Qt/5.8/ios/mkspecs/features/resolve_config.prf \
		../../Qt/5.8/ios/mkspecs/features/uikit/resolve_config.prf \
		../../Qt/5.8/ios/mkspecs/features/default_post.prf \
		../../Qt/5.8/ios/mkspecs/features/mac/default_post.prf \
		../../Qt/5.8/ios/mkspecs/features/uikit/default_post.prf \
		../../Qt/5.8/ios/mkspecs/macx-ios-clang/features/default_post.prf \
		../../Qt/5.8/ios/mkspecs/features/mac/objective_c.prf \
		../../Qt/5.8/ios/mkspecs/features/qml_debug.prf \
		../../Qt/5.8/ios/mkspecs/features/uikit/bitcode.prf \
		../../Qt/5.8/ios/mkspecs/features/warn_on.prf \
		../../Qt/5.8/ios/mkspecs/features/qt.prf \
		../../Qt/5.8/ios/mkspecs/features/uikit/qt.prf \
		../../Qt/5.8/ios/mkspecs/features/resources.prf \
		../../Qt/5.8/ios/mkspecs/features/moc.prf \
		../../Qt/5.8/ios/mkspecs/features/unix/thread.prf \
		../../Qt/5.8/ios/mkspecs/features/qmake_use.prf \
		../../Qt/5.8/ios/mkspecs/features/file_copies.prf \
		../../Qt/5.8/ios/mkspecs/features/mac/rez.prf \
		../../Qt/5.8/ios/mkspecs/features/mac/asset_catalogs.prf \
		../../Qt/5.8/ios/mkspecs/features/testcase_targets.prf \
		../../Qt/5.8/ios/mkspecs/features/uikit/testcase_targets.prf \
		../../Qt/5.8/ios/mkspecs/features/exceptions.prf \
		../../Qt/5.8/ios/mkspecs/features/yacc.prf \
		../../Qt/5.8/ios/mkspecs/features/lex.prf \
		../SampleQTLib/SampleQTLib.pro \
		../../Qt/5.8/ios/lib/libQt5Core_debug.prl
	$(QMAKE) -o Makefile ../SampleQTLib/SampleQTLib.pro -spec macx-ios-clang CONFIG+=iphonesimulator CONFIG+=simulator CONFIG+=qml_debug
../../Qt/5.8/ios/mkspecs/features/spec_pre.prf:
../../Qt/5.8/ios/mkspecs/qdevice.pri:
../../Qt/5.8/ios/mkspecs/features/device_config.prf:
../../Qt/5.8/ios/mkspecs/common/unix.conf:
../../Qt/5.8/ios/mkspecs/common/mac.conf:
../../Qt/5.8/ios/mkspecs/common/uikit.conf:
../../Qt/5.8/ios/mkspecs/common/ios.conf:
../../Qt/5.8/ios/mkspecs/common/sanitize.conf:
../../Qt/5.8/ios/mkspecs/common/gcc-base.conf:
../../Qt/5.8/ios/mkspecs/common/gcc-base-mac.conf:
../../Qt/5.8/ios/mkspecs/common/clang.conf:
../../Qt/5.8/ios/mkspecs/common/clang-mac.conf:
../../Qt/5.8/ios/mkspecs/common/ios/clang.conf:
../../Qt/5.8/ios/mkspecs/common/ios/qmake.conf:
../../Qt/5.8/ios/mkspecs/qconfig.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dcore.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dcore_private.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dextras.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dextras_private.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dinput.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dinput_private.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dlogic.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dquick.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dquick_private.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dquickextras.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dquickinput.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dquickrender.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_3drender.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_3drender_private.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_bluetooth.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_charts.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_charts_private.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_clipboard_support_private.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_clucene_private.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_concurrent.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_core.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_core_private.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_datavisualization.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_fb_support_private.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_gamepad.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_gamepad_private.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_graphics_support_private.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_gui.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_gui_private.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_help.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_help_private.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_location.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_location_private.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_multimedia.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_network.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_network_private.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_networkauth.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_networkauth_private.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_nfc.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_nfc_private.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_opengl.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_opengl_private.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_openglextensions.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_positioning.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_positioning_private.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_printsupport.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_purchasing.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_purchasing_private.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_qml.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_qml_private.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_qmltest.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_quick.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_quick_private.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_script.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_script_private.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_scripttools.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_scxml.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_scxml_private.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_sensors.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_sensors_private.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_sql.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_sql_private.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_svg.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_svg_private.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_testlib.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_testlib_private.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_texttospeech.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_theme_support_private.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_uiplugin.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_uitools.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_uitools_private.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_webchannel.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_webchannel_private.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_websockets.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_websockets_private.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_webview.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_webview_private.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_widgets.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_widgets_private.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_xml.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_xml_private.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_lib_zlib_private.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_plugin_darwingamepad.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_plugin_gltfsceneio.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qavfcamera.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qavfmediaplayer.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qgenericbearer.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qgif.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qicns.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qico.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qios.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qiosnsphotolibrarysupport.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qjpeg.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qmacjp2.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qminimal.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qmldbg_debugger.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qmldbg_inspector.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qmldbg_local.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qmldbg_native.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qmldbg_profiler.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qmldbg_quickprofiler.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qmldbg_server.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qmldbg_tcp.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qoffscreen.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qsqlite.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qsvg.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qsvgicon.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtaudio_coreaudio.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtexttospeech_speechios.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtga.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtgeoservices_esri.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtgeoservices_mapbox.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtgeoservices_nokia.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtgeoservices_osm.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtiff.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtposition_cl.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtsensors_generic.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtsensors_ios.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qwbmp.pri:
../../Qt/5.8/ios/mkspecs/modules/qt_plugin_qwebp.pri:
../../Qt/5.8/ios/mkspecs/features/qt_functions.prf:
../../Qt/5.8/ios/mkspecs/features/qt_config.prf:
../../Qt/5.8/ios/mkspecs/features/uikit/qt_config.prf:
../../Qt/5.8/ios/mkspecs/macx-ios-clang/qmake.conf:
../../Qt/5.8/ios/mkspecs/features/spec_post.prf:
.qmake.stash:
../../Qt/5.8/ios/mkspecs/features/exclusive_builds.prf:
../../Qt/5.8/ios/mkspecs/features/mac/sdk.prf:
../../Qt/5.8/ios/mkspecs/features/uikit/sdk.prf:
../../Qt/5.8/ios/mkspecs/features/toolchain.prf:
../../Qt/5.8/ios/mkspecs/features/mac/toolchain.prf:
../../Qt/5.8/ios/mkspecs/features/default_pre.prf:
../../Qt/5.8/ios/mkspecs/features/mac/default_pre.prf:
../../Qt/5.8/ios/mkspecs/features/uikit/default_pre.prf:
../../Qt/5.8/ios/mkspecs/features/resolve_config.prf:
../../Qt/5.8/ios/mkspecs/features/uikit/resolve_config.prf:
../../Qt/5.8/ios/mkspecs/features/default_post.prf:
../../Qt/5.8/ios/mkspecs/features/mac/default_post.prf:
../../Qt/5.8/ios/mkspecs/features/uikit/default_post.prf:
../../Qt/5.8/ios/mkspecs/macx-ios-clang/features/default_post.prf:
../../Qt/5.8/ios/mkspecs/features/mac/objective_c.prf:
../../Qt/5.8/ios/mkspecs/features/qml_debug.prf:
../../Qt/5.8/ios/mkspecs/features/uikit/bitcode.prf:
../../Qt/5.8/ios/mkspecs/features/warn_on.prf:
../../Qt/5.8/ios/mkspecs/features/qt.prf:
../../Qt/5.8/ios/mkspecs/features/uikit/qt.prf:
../../Qt/5.8/ios/mkspecs/features/resources.prf:
../../Qt/5.8/ios/mkspecs/features/moc.prf:
../../Qt/5.8/ios/mkspecs/features/unix/thread.prf:
../../Qt/5.8/ios/mkspecs/features/qmake_use.prf:
../../Qt/5.8/ios/mkspecs/features/file_copies.prf:
../../Qt/5.8/ios/mkspecs/features/mac/rez.prf:
../../Qt/5.8/ios/mkspecs/features/mac/asset_catalogs.prf:
../../Qt/5.8/ios/mkspecs/features/testcase_targets.prf:
../../Qt/5.8/ios/mkspecs/features/uikit/testcase_targets.prf:
../../Qt/5.8/ios/mkspecs/features/exceptions.prf:
../../Qt/5.8/ios/mkspecs/features/yacc.prf:
../../Qt/5.8/ios/mkspecs/features/lex.prf:
../SampleQTLib/SampleQTLib.pro:
../../Qt/5.8/ios/lib/libQt5Core_debug.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile ../SampleQTLib/SampleQTLib.pro -spec macx-ios-clang CONFIG+=iphonesimulator CONFIG+=simulator CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../SampleQTLib/sampleqtlib.h $(DISTDIR)/
	$(COPY_FILE) --parents ../SampleQTLib/sampleqtlib.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

sampleqtlib.o: ../SampleQTLib/sampleqtlib.cpp ../SampleQTLib/sampleqtlib.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sampleqtlib.o ../SampleQTLib/sampleqtlib.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/usr/lib || mkdir -p $(INSTALL_ROOT)/usr/lib
	-$(INSTALL_FILE) $(TARGET) $(INSTALL_ROOT)/usr/lib/$(TARGET)
	$(RANLIB) $(INSTALL_ROOT)/usr/lib/$(TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/usr/lib/$(TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/lib/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

